# Generated by Django 3.2.9 on 2021-12-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaszlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baszlUser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=300)),
                ('accessSecret', models.CharField(max_length=300)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('numPosts', models.IntegerField(default=0)),
                ('baszlAcct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baszlaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('numPosts', models.IntegerField(default=0)),
                ('baszlAcct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baszlaccount')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=300)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('numPosts', models.IntegerField(default=0)),
                ('baszlAcct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baszlaccount')),
            ],
        ),
    ]
