# Generated by Django 3.2.9 on 2021-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='accessSecret',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='accessToken',
            field=models.BinaryField(),
        ),
    ]
