# Generated by Django 3.2.9 on 2021-11-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BaszlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baszlUser', models.CharField(max_length=200)),
                ('baszlPass', models.CharField(max_length=200)),
                ('facebookAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to='main.socialmediaaccount')),
                ('instagramAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='main.socialmediaaccount')),
                ('twitterAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='main.socialmediaaccount')),
            ],
        ),
    ]
