# Generated by Django 3.2.9 on 2021-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211203_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='accessSecret',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='accessToken',
            field=models.CharField(max_length=300),
        ),
    ]
