# Generated by Django 3.2.9 on 2021-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211203_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='timeStamp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
