# Generated by Django 3.2.9 on 2021-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_twitteraccount_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='timeStamp',
            field=models.IntegerField(default=0),
        ),
    ]
