# Generated by Django 3.2.9 on 2021-12-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211126_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=300)),
                ('handle', models.CharField(max_length=200)),
                ('numPosts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('numPosts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=300)),
                ('accessSecretToken', models.CharField(max_length=300)),
                ('handle', models.CharField(max_length=200)),
                ('numPosts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='baszlaccount',
            name='baszlPass',
        ),
        migrations.AlterField(
            model_name='baszlaccount',
            name='facebookAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facebookaccount'),
        ),
        migrations.AlterField(
            model_name='baszlaccount',
            name='instagramAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instagramaccount'),
        ),
        migrations.AlterField(
            model_name='baszlaccount',
            name='twitterAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.twitteraccount'),
        ),
        migrations.DeleteModel(
            name='SocialMediaAccount',
        ),
    ]
