# Generated by Django 3.2.9 on 2021-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_twitteraccount_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='timeStamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='timeStamp',
            field=models.IntegerField(default=0),
        ),
    ]
