# Generated by Django 3.2.9 on 2021-12-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211203_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='accessToken',
            field=models.CharField(max_length=400),
        ),
    ]
