# Generated by Django 3.2.9 on 2021-12-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_facebookaccount_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='userID',
            field=models.CharField(default=8675309, max_length=100),
            preserve_default=False,
        ),
    ]
