# Generated by Django 3.2.9 on 2021-12-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_facebookaccount_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='pageID',
            field=models.CharField(default=2023, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookaccount',
            name='pageToken',
            field=models.CharField(default=2023, max_length=400),
            preserve_default=False,
        ),
    ]
