# Generated by Django 3.2.9 on 2021-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='pageID',
            field=models.CharField(max_length=200),
        ),
    ]
