# Generated by Django 3.2.9 on 2021-12-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_facebookaccount_pageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='handle',
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
