# Generated by Django 3.2.9 on 2021-12-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211204_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baszlAcct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baszlaccount')),
            ],
        ),
    ]
