# Generated by Django 3.2.9 on 2021-12-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_baszlaccount_errorcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baszlaccount',
            old_name='errorCode',
            new_name='statusCodes',
        ),
    ]
