# Generated by Django 3.2.9 on 2021-12-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_errorcode_baszlaccount_statuscodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='password',
            new_name='accountID',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='username',
        ),
    ]
