# Generated by Django 3.2.9 on 2021-12-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211206_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
